### ISSUE TITLE
Add CLI option to adjust show time for the notification

### ISSUE THREAD

**Issue by linuxer0x42** [ikrivosheev/pa-notify#1]
This would be very handy, as of current in my opinion the notification stays up too long, it would be handy if there was a CLI option to adjust the notification time.

This is a very handy application, thanks for making this!

**Comment by ikrivosheev** [comment]
Thank you for the report! I add new option: `-t, --timeout` - which set timeout for notification

Done: https://github.com/ikrivosheev/pa-notify/releases/tag/v1.3.0
