### ISSUE TITLE
`pa-notify` stuck when started as systemd service

### ISSUE THREAD

**Issue by Flowneee** [ikrivosheev/pa-notify#2]
I'm trying to run `pa-notify` as user systemd service on login

```
[Unit]
Description=PulseAudio or PipeWire volume notification.

[Service]
Environment=G_MESSAGES_DEBUG=all
ExecStart=/usr/bin/pa-notify

[Install]
WantedBy=default.target
```

But `pa-notify` get stuck with following log

```
Dec 13 00:14:46 archlinux systemd[26769]: Started PulseAudio or PipeWire volume notification..
Dec 13 00:14:46 archlinux pa-notify[26779]: Options have been initialized
Dec 13 00:14:46 archlinux pa-notify[26779]: Notify has been initialized
Dec 13 00:14:46 archlinux pa-notify[26779]: pa_mainloop_new
Dec 13 00:14:46 archlinux pa-notify[26779]: pa_mainloop_get_api
Dec 13 00:14:46 archlinux pa-notify[26779]: pa_signal_new SIGINT SIGTERM
Dec 13 00:14:46 archlinux pa-notify[26779]: pa_context_new
Dec 13 00:14:46 archlinux pa-notify[26779]: pa_context_connect
Dec 13 00:14:46 archlinux pa-notify[26779]: pa_context_set_state_callback
Dec 13 00:14:46 archlinux pa-notify[26779]: PulseAudio has been initialized
Dec 13 00:14:46 archlinux pa-notify[26779]: Run loop
Dec 13 00:14:46 archlinux pa-notify[26779]: PulseAudio connection established.
Dec 13 00:14:46 archlinux pa-notify[26779]: New event
Dec 13 00:14:46 archlinux pa-notify[26779]: Sink info
Dec 13 00:14:46 archlinux pa-notify[26779]: SNAP name: (null)
Dec 13 00:14:46 archlinux pa-notify[26779]: SNAP app: (null)
Dec 13 00:14:46 archlinux pa-notify[26779]: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
```

I also tried to add After/Requires on pipewire and pipewire-pulse services, as well as add TimeoutStartSec, but nothing works. If I start it manually from console (either as `$ pa-notify` or `$ systemctl --user start pa-notify`) it works.

UPD: 

I noticed that it unstuck after some time

```
Dec 13 00:14:46 archlinux pa-notify[26779]: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
Dec 13 00:15:11 archlinux pa-notify[26779]: Sink info
Dec 13 00:15:11 archlinux pa-notify[26779]: New event
```

**Comment by ikrivosheev** [comment]
@Flowneee hello! Thank you for the issue. Is pa-notify systemd service a user service?

**Comment by Flowneee** [comment]
Yes, it is a user service in `~/.config/systemd/user`.

**Comment by ikrivosheev** [comment]
@Flowneee hmm, very interested. Can you show how you started your default.target?

**Comment by Flowneee** [comment]
It's started automatically on login. I don't know exact mechanism, it is default provided target. Here is some explanation https://wiki.archlinux.org/title/systemd/User#How_it_works, basically they say it is started from PAM module.

**Comment by ikrivosheev** [comment]
@Flowneee thank you for the explanation. I will try to reproduce it on my laptop. Because I have a custom target which started in i3 config.

**Comment by Flowneee** [comment]
I thought about something like that also since many of my software in autostart doesn't work very well with default.target and I don't like to start applications from i3 config. Probably will do this.

If you need any further info, please let me know.

**Comment by ikrivosheev** [comment]
@Flowneee here is my i3 config and startup custom systemd target: https://github.com/ikrivosheev/dotfiles/blob/master/.config/i3/config#L247

A lot of things does not work with `default.target` because it starts before wm. Well, i am not shure, but it can be similar situation. I'll try to figure out what's going wrong. If you have some thoughts - welcome)

**Comment by Flowneee** [comment]
Thanks for your help!

This is obviously incorrect bug report, I apologize. And I gonna close this issue since there is no problem.

I figured it out. My notification server (dunst) is starting in some weird way - using "dbus autostart" https://techbase.kde.org/Development/Tutorials/D-Bus/Autostart_Services, and it seems like it takes too long for it to start notification server, thus I said "pa-notify unstuck".

Custom target is working perfectly thought.

**Comment by ikrivosheev** [comment]
@Flowneee great! Thank you for the answer)
